
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        
    - name: Copy artifact to root
      run: |
        mkdir -p .tmp
        cp dist/windows/main.exe .tmp/main.exe

    - name: Commit and push artifact
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        cp .tmp/main.exe ./main.exe
        git add main.exe
        git commit -m 'Add compiled .exe to repository'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}