
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - name: Copy artifact to root
      run: |
        cp -fr dist/windows/main.exe main.exe
        sudo rm -rf dist

    - name: Commit and push artifact
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Commit compiled artifact