name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a GitHub release?'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'
      version_name:
        description: 'Version name or number'
        required: false  # Not required initially
        default: ''
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Rename binary
      run: |
        cp -fr src/dist/windows/main.exe src/dist/windows/ad-sync.exe
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ad-sync
        path: src/dist/windows/ad-sync.exe
        if-no-files-found: error

    - name: Create GitHub Release
      if: "${{ github.event.inputs.create_release == 'yes' }}"
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        name: ${{github.event.inputs.version_name}}
        files: src/dist/windows/ad-sync.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}